version: 2

sources:
  - name: staging

    # for bigquery
    database: data-eng-camp-apr22
    schema: Mage_data_engineer
    tables:
      - name: green_trip_january_2020
      - name: green_trip_february_2020
      - name: green_trip_march_2020
      - name: green_trip_april_2020